# Loki Stack Configuration
loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  config:
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    ruler:
      alertmanager_url: http://alertmanager:9093

    limits_config:
      retention_period: 168h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 9080
    clients:
      - url: http://loki:3100/loki/api/v1/push

    snippets:
      extraScrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_controller_name]
              regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
              action: replace
              target_label: __tmp_controller_name
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app, __tmp_controller_name, __meta_kubernetes_pod_name]
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_label_component]
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: component
            - source_labels: [__meta_kubernetes_namespace]
              action: replace
              target_label: kubernetes_namespace
            - source_labels: [__meta_kubernetes_pod_name]
              action: replace
              target_label: kubernetes_pod_name
            - source_labels: [__meta_kubernetes_pod_container_name]
              action: replace
              target_label: kubernetes_container_name
            - source_labels: [__meta_kubernetes_pod_node_name]
              action: replace
              target_label: kubernetes_node_name

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

grafana:
  enabled: false  # We'll use our existing Grafana installation

# Service configuration
service:
  type: ClusterIP
  port: 3100
  targetPort: 3100

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {} 